### ISSUE TITLE
How to add new item if it not found in QuickBooks via web connector?

### ISSUE THREAD

**Issue by MarErm27** [cv3/QuickBooksWebConnector#2]
Hello! I was wondering if I can ask here, how to add a new item if it's not found in QuickBooks by web connector? I'm trying to add an invoice but it says that it can't find an item reference. Please, help

InvoiceQueryRsType: A query request did not find a matching object in QuickBooks

**Comment by pageben** [comment]
At this time, this app does the following API calls to QuickBooks:

- CustomerQueryRs
- CustomerMsgQueryRs
- CustomerModRs
- SalesOrderAddRs
- SalesReceiptAddRs
- InventoryAddRs
- ItemGroupAddRs
- ItemQueryRs
- CustomerAddRs

The most typical use-case with CommerceV3 is when a business running QuickBooks needs to get orders from their website into QuickBooks via Sales Order or Sales Receipt.  Invoices haven't been a necessary feature for these scenarios.

What you want is probably InvoiceAdd.  Check the [QuickBooks Desktop API Reference](https://developer.intuit.com/app/developer/qbdesktop/docs/api-reference/qbdesktop) for more information.

**Comment by pageben** [comment]
You may be able to create the new items for your invoices in QuickBooks by customizing func ImportCV3ItemsToQB (in qbwcGo/qbwcImportCV3ItemsToQB.go)

**Comment by MarErm27** [comment]
> 
> 
> At this time, this app does the following API calls to QuickBooks:
> 
>     * CustomerQueryRs
> 
>     * CustomerMsgQueryRs
> 
>     * CustomerModRs
> 
>     * SalesOrderAddRs
> 
>     * SalesReceiptAddRs
> 
>     * InventoryAddRs
> 
>     * ItemGroupAddRs
> 
>     * ItemQueryRs
> 
>     * CustomerAddRs
> 
> 
> The most typical use-case with CommerceV3 is when a business running QuickBooks needs to get orders from their website into QuickBooks via Sales Order or Sales Receipt. Invoices haven't been a necessary feature for these scenarios.
> 
> What you want is probably InvoiceAdd. Check the [QuickBooks Desktop API Reference](https://developer.intuit.com/app/developer/qbdesktop/docs/api-reference/qbdesktop) for more information.

So to add an item I need to use ItemServiceAddRs
I need to create an XML file wit fields shown [here](https://developer.intuit.com/app/developer/qbdesktop/docs/api-reference/qbdesktop/iteminventoryadd) at the request and it will create an item with item reference, after that it will return the item reference. Did I get it?

Or I need to use ItemServiceAddRs somehow?

**Comment by MarErm27** [comment]
Here is a function in Java how to add customer
```
  public String addCustomer() throws QBDB.DbException, JAXBException, URISyntaxException, IOException, ClassNotFoundException {
    Input input = getInput();
    List<Invoice> invoices = input.getInvoices();
    String xml = "";
    QBXML qbXML = new QBXML();
    QBXMLMsgsRq xmlMsgRq = new QBXMLMsgsRq();
    xmlMsgRq.setOnError("continueOnError");
    qbXML.setQBXMLMsgsRq(xmlMsgRq);

    List<Object> reqList = xmlMsgRq.getHostQueryRqOrCompanyQueryRqOrCompanyActivityQueryRq();
    int i = 1;

    for (Invoice invoice : invoices) {

      CustomerRef ref = getCustomerRefForEmail(invoice.getEmail());
      String idChk = ref.getListID();
      if (idChk.equals("-1")) {
        CustomerAddRqType customerAddRq = new CustomerAddRqType();
        reqList.add(customerAddRq);
        customerAddRq.setRequestID(i++ + "");
        CustomerAdd cust = new CustomerAdd();
        customerAddRq.setCustomerAdd(cust);
        // 	cust.setEmail(invoice.getEmail());//email);
        cust.setName("watchmaxx");
        cust.setFirstName(invoice.getEmail());
        cust.setCompanyName("watchmaxx");
      }
    }
    xml = getRequestXml(qbXML);
    return xml;
  }
```

how to add an item by analog?

**Comment by MarErm27** [comment]
I made a function below, but I'm not sure how to set a listId field, it's not available. I was reading your code here (qbwcGo/qbwcImportCV3ItemsToQB.go) and I can't find you setting listId is it possible?

  public String addItem(String itemRefName) throws QBDB.DbException, JAXBException, URISyntaxException, IOException, ClassNotFoundException {
    String[] itemData = itemRefName.split(":", 2);
    System.out.println("=> item name" + itemData[0]);
    System.out.println("=> item ref" + itemData[1]);
    String xml = "";
    QBXML qbXML = new QBXML();
    QBXMLMsgsRq xmlMsgRq = new QBXMLMsgsRq();
    xmlMsgRq.setOnError("continueOnError");
    qbXML.setQBXMLMsgsRq(xmlMsgRq);

    List<Object> reqList = xmlMsgRq.getHostQueryRqOrCompanyQueryRqOrCompanyActivityQueryRq();
    int i = 1;
        ItemInventoryAddRqType itemAddRq = new ItemInventoryAddRqType();
        reqList.add(itemAddRq);
        ItemInventoryAdd item = new ItemInventoryAdd();
        itemAddRq.setItemInventoryAdd(item);
        item.setName(itemRefName+"Marat");
       // item.setListId
    xml = getRequestXml(qbXML);
    return xml;
  }

here is a list of available fields may one of them be an alias for listId?
    @XmlElement(name = "ListID")
    protected String listID;
    @XmlElement(name = "TimeCreated")
    @XmlSchemaType(name = "anySimpleType")
    protected String timeCreated;
    @XmlElement(name = "TimeModified")
    @XmlSchemaType(name = "anySimpleType")
    protected String timeModified;
    @XmlElement(name = "EditSequence")
    protected String editSequence;
    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "BarCodeValue")
    protected String barCodeValue;
    @XmlElement(name = "IsActive")
    @XmlSchemaType(name = "anySimpleType")
    protected String isActive;
    @XmlElement(name = "ClassRef")
    protected ClassRef classRef;
    @XmlElement(name = "ItemDesc")
    protected String itemDesc;
    @XmlElement(name = "TaxRate")
    protected String taxRate;
    @XmlElement(name = "TaxVendorRef")
    protected TaxVendorRef taxVendorRef;
    @XmlElement(name = "SalesTaxReturnLineRef")
    protected SalesTaxReturnLineRef salesTaxReturnLineRef;
    @XmlElement(name = "ExternalGUID")
    protected String externalGUID;
    @XmlElement(name = "DataExtRet")
    protected List<DataExtRet> dataExtRet;
    @XmlAttribute(name = "Hjid")
    protected Long hjid;

**Comment by MarErm27** [comment]
I've found listId in class ref and rewrote the method
```
  public String addItem(String itemRefName) throws QBDB.DbException, JAXBException, URISyntaxException, IOException, ClassNotFoundException {
    String[] itemData = itemRefName.split(":", 2);
    System.out.println("=> item name" + itemData[0]);
    System.out.println("=> item ref" + itemData[1]);
    String xml = "";
    QBXML qbXML = new QBXML();
    QBXMLMsgsRq xmlMsgRq = new QBXMLMsgsRq();
    xmlMsgRq.setOnError("continueOnError");
    qbXML.setQBXMLMsgsRq(xmlMsgRq);

    List<Object> reqList = xmlMsgRq.getHostQueryRqOrCompanyQueryRqOrCompanyActivityQueryRq();

    ItemInventoryAddRqType itemAddRq = new ItemInventoryAddRqType();
    reqList.add(itemAddRq);
    ItemInventoryAdd item = new ItemInventoryAdd();
    itemAddRq.setItemInventoryAdd(item);
    ClassRef classRef = new ClassRef();
    classRef.setFullName(itemData[0]);
    classRef.setListID(itemData[0]);
    item.setClassRef(classRef);
    xml = getRequestXml(qbXML);
    return xml;
  }
```
Now I'm trying to find out how to send this to web connector

**Comment by MarErm27** [comment]
What is the idiom of communication with QuickBooks web connector?

**Comment by MarErm27** [comment]
What is the difference between ItemInventoryRet and ItemInventoryAdd?

**Comment by pageben** [comment]
Java development is beyond the scope of this project.  You may find examples specific to your application at Intuit here - [https://developer.intuit.com/app/developer/qbo/docs/develop/sdks-and-samples-collections/java](https://developer.intuit.com/app/developer/qbo/docs/develop/sdks-and-samples-collections/java)

For more QuickBooks development help, you'll probably find answers at the Intuit Developer Blog, or Intuit's Github, linked here - [https://developer.intuit.com/app/developer/homepage](https://developer.intuit.com/app/developer/homepage)

For CV3 specific issues, contact support@commercev3.com

**Comment by MarErm27** [comment]
Thank you

**Comment by MarErm27** [comment]
@pageben I was wondering if I can ask you one more time, I've created an XML to add an item, how to send it to QuickBooks?

I have a function sendRequestXML and I put the XML in return, but items it not getting created. Do I need to use sendRequestXML or receiveResponseXML for this purpose?
